# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fitpannelgui.ui'
#
# Created: Wed Mar 19 21:12:42 2014
#	  by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	_fromUtf8 = lambda s: s

class Ui_fitpannel(object):
	def setupUi(self, fitpannel):
		fitpannel.setObjectName(_fromUtf8("fitpannel"))
		fitpannel.resize(671, 263)
		self.centralwidget = QtGui.QWidget(fitpannel)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.gauss = QtGui.QWidget()
		self.gauss.setObjectName(_fromUtf8("gauss"))
		self.verticalLayout_2 = QtGui.QVBoxLayout(self.gauss)
		self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
		self.gridLayout = QtGui.QGridLayout()
		self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
		self.gauss_a_min = QtGui.QLineEdit(self.gauss)
		self.gauss_a_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_a_min.setObjectName(_fromUtf8("gauss_a_min"))
		self.gridLayout.addWidget(self.gauss_a_min, 5, 2, 1, 1)
		self.label_15 = QtGui.QLabel(self.gauss)
		self.label_15.setObjectName(_fromUtf8("label_15"))
		self.gridLayout.addWidget(self.label_15, 2, 1, 1, 1)
		self.do_gaussfit = QtGui.QPushButton(self.gauss)
		self.do_gaussfit.setMinimumSize(QtCore.QSize(134, 0))
		self.do_gaussfit.setObjectName(_fromUtf8("do_gaussfit"))
		self.gridLayout.addWidget(self.do_gaussfit, 8, 4, 1, 1)
		self.label_5 = QtGui.QLabel(self.gauss)
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
		self.gauss_mean_err = QtGui.QLabel(self.gauss)
		self.gauss_mean_err.setText(_fromUtf8(""))
		self.gauss_mean_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_mean_err.setObjectName(_fromUtf8("gauss_mean_err"))
		self.gridLayout.addWidget(self.gauss_mean_err, 3, 4, 1, 1)
		self.label_2 = QtGui.QLabel(self.gauss)
		self.label_2.setMinimumSize(QtCore.QSize(133, 0))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
		self.label_14 = QtGui.QLabel(self.gauss)
		self.label_14.setObjectName(_fromUtf8("label_14"))
		self.gridLayout.addWidget(self.label_14, 2, 3, 1, 1)
		self.gauss_b_min = QtGui.QLineEdit(self.gauss)
		self.gauss_b_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_b_min.setObjectName(_fromUtf8("gauss_b_min"))
		self.gridLayout.addWidget(self.gauss_b_min, 6, 2, 1, 1)
		self.gauss_b = QtGui.QLineEdit(self.gauss)
		self.gauss_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_b.setObjectName(_fromUtf8("gauss_b"))
		self.gridLayout.addWidget(self.gauss_b, 6, 1, 1, 1)
		self.gauss_sigma = QtGui.QLineEdit(self.gauss)
		self.gauss_sigma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_sigma.setObjectName(_fromUtf8("gauss_sigma"))
		self.gridLayout.addWidget(self.gauss_sigma, 4, 1, 1, 1)
		self.label_13 = QtGui.QLabel(self.gauss)
		self.label_13.setObjectName(_fromUtf8("label_13"))
		self.gridLayout.addWidget(self.label_13, 2, 2, 1, 1)
		self.gauss_a_err = QtGui.QLabel(self.gauss)
		self.gauss_a_err.setText(_fromUtf8(""))
		self.gauss_a_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_a_err.setObjectName(_fromUtf8("gauss_a_err"))
		self.gridLayout.addWidget(self.gauss_a_err, 5, 4, 1, 1)
		self.gauss_sigma_max = QtGui.QLineEdit(self.gauss)
		self.gauss_sigma_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_sigma_max.setObjectName(_fromUtf8("gauss_sigma_max"))
		self.gridLayout.addWidget(self.gauss_sigma_max, 4, 3, 1, 1)
		self.label_4 = QtGui.QLabel(self.gauss)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
		self.gauss_mean = QtGui.QLineEdit(self.gauss)
		self.gauss_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_mean.setObjectName(_fromUtf8("gauss_mean"))
		self.gridLayout.addWidget(self.gauss_mean, 3, 1, 1, 1)
		self.label = QtGui.QLabel(self.gauss)
		self.label.setObjectName(_fromUtf8("label"))
		self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
		self.gauss_sigma_err = QtGui.QLabel(self.gauss)
		self.gauss_sigma_err.setText(_fromUtf8(""))
		self.gauss_sigma_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_sigma_err.setObjectName(_fromUtf8("gauss_sigma_err"))
		self.gridLayout.addWidget(self.gauss_sigma_err, 4, 4, 1, 1)
		self.gauss_mean_min = QtGui.QLineEdit(self.gauss)
		self.gauss_mean_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_mean_min.setObjectName(_fromUtf8("gauss_mean_min"))
		self.gridLayout.addWidget(self.gauss_mean_min, 3, 2, 1, 1)
		self.label_6 = QtGui.QLabel(self.gauss)
		self.label_6.setObjectName(_fromUtf8("label_6"))
		self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
		self.gauss_b_max = QtGui.QLineEdit(self.gauss)
		self.gauss_b_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_b_max.setObjectName(_fromUtf8("gauss_b_max"))
		self.gridLayout.addWidget(self.gauss_b_max, 6, 3, 1, 1)
		self.gauss_b_err = QtGui.QLabel(self.gauss)
		self.gauss_b_err.setText(_fromUtf8(""))
		self.gauss_b_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_b_err.setObjectName(_fromUtf8("gauss_b_err"))
		self.gridLayout.addWidget(self.gauss_b_err, 6, 4, 1, 1)
		self.gauss_sigma_min = QtGui.QLineEdit(self.gauss)
		self.gauss_sigma_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_sigma_min.setObjectName(_fromUtf8("gauss_sigma_min"))
		self.gridLayout.addWidget(self.gauss_sigma_min, 4, 2, 1, 1)
		self.gauss_mean_max = QtGui.QLineEdit(self.gauss)
		self.gauss_mean_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_mean_max.setObjectName(_fromUtf8("gauss_mean_max"))
		self.gridLayout.addWidget(self.gauss_mean_max, 3, 3, 1, 1)
		self.label_3 = QtGui.QLabel(self.gauss)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
		self.gauss_a_max = QtGui.QLineEdit(self.gauss)
		self.gauss_a_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_a_max.setObjectName(_fromUtf8("gauss_a_max"))
		self.gridLayout.addWidget(self.gauss_a_max, 5, 3, 1, 1)
		self.gauss_a = QtGui.QLineEdit(self.gauss)
		self.gauss_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_a.setObjectName(_fromUtf8("gauss_a"))
		self.gridLayout.addWidget(self.gauss_a, 5, 1, 1, 1)
		self.gauss_num_signal = QtGui.QLabel(self.gauss)
		self.gauss_num_signal.setText(_fromUtf8(""))
		self.gauss_num_signal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_num_signal.setObjectName(_fromUtf8("gauss_num_signal"))
		self.gridLayout.addWidget(self.gauss_num_signal, 7, 3, 1, 1)
		self.label_8 = QtGui.QLabel(self.gauss)
		self.label_8.setObjectName(_fromUtf8("label_8"))
		self.gridLayout.addWidget(self.label_8, 7, 2, 1, 1)
		self.gauss_num_signal_err = QtGui.QLabel(self.gauss)
		self.gauss_num_signal_err.setText(_fromUtf8(""))
		self.gauss_num_signal_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.gauss_num_signal_err.setObjectName(_fromUtf8("gauss_num_signal_err"))
		self.gridLayout.addWidget(self.gauss_num_signal_err, 7, 4, 1, 1)
		self.gauss_del_fit = QtGui.QPushButton(self.gauss)
		self.gauss_del_fit.setObjectName(_fromUtf8("gauss_del_fit"))
		self.gridLayout.addWidget(self.gauss_del_fit, 8, 3, 1, 1)
		self.verticalLayout_2.addLayout(self.gridLayout)
		self.tabWidget.addTab(self.gauss, _fromUtf8(""))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
		self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
		self.gridLayout_3 = QtGui.QGridLayout()
		self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
		self.label_18 = QtGui.QLabel(self.tab_2)
		self.label_18.setObjectName(_fromUtf8("label_18"))
		self.gridLayout_3.addWidget(self.label_18, 3, 0, 1, 1)
		self.label_20 = QtGui.QLabel(self.tab_2)
		self.label_20.setObjectName(_fromUtf8("label_20"))
		self.gridLayout_3.addWidget(self.label_20, 0, 1, 1, 1)
		self.bw_a = QtGui.QLineEdit(self.tab_2)
		self.bw_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_a.setObjectName(_fromUtf8("bw_a"))
		self.gridLayout_3.addWidget(self.bw_a, 5, 1, 1, 1)
		self.bw_b_err = QtGui.QLabel(self.tab_2)
		self.bw_b_err.setText(_fromUtf8(""))
		self.bw_b_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_b_err.setObjectName(_fromUtf8("bw_b_err"))
		self.gridLayout_3.addWidget(self.bw_b_err, 6, 4, 1, 1)
		self.bw_b = QtGui.QLineEdit(self.tab_2)
		self.bw_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_b.setObjectName(_fromUtf8("bw_b"))
		self.gridLayout_3.addWidget(self.bw_b, 6, 1, 1, 1)
		self.label_17 = QtGui.QLabel(self.tab_2)
		self.label_17.setObjectName(_fromUtf8("label_17"))
		self.gridLayout_3.addWidget(self.label_17, 5, 0, 1, 1)
		self.do_bwfit = QtGui.QPushButton(self.tab_2)
		self.do_bwfit.setObjectName(_fromUtf8("do_bwfit"))
		self.gridLayout_3.addWidget(self.do_bwfit, 8, 4, 1, 1)
		self.bw_mean = QtGui.QLineEdit(self.tab_2)
		self.bw_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_mean.setObjectName(_fromUtf8("bw_mean"))
		self.gridLayout_3.addWidget(self.bw_mean, 3, 1, 1, 1)
		self.label_24 = QtGui.QLabel(self.tab_2)
		self.label_24.setObjectName(_fromUtf8("label_24"))
		self.gridLayout_3.addWidget(self.label_24, 0, 4, 1, 1)
		self.bw_a_err = QtGui.QLabel(self.tab_2)
		self.bw_a_err.setText(_fromUtf8(""))
		self.bw_a_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_a_err.setObjectName(_fromUtf8("bw_a_err"))
		self.gridLayout_3.addWidget(self.bw_a_err, 5, 4, 1, 1)
		self.bw_width_max = QtGui.QLineEdit(self.tab_2)
		self.bw_width_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_width_max.setObjectName(_fromUtf8("bw_width_max"))
		self.gridLayout_3.addWidget(self.bw_width_max, 4, 3, 1, 1)
		self.bw_b_min = QtGui.QLineEdit(self.tab_2)
		self.bw_b_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_b_min.setObjectName(_fromUtf8("bw_b_min"))
		self.gridLayout_3.addWidget(self.bw_b_min, 6, 2, 1, 1)
		self.bw_a_min = QtGui.QLineEdit(self.tab_2)
		self.bw_a_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_a_min.setObjectName(_fromUtf8("bw_a_min"))
		self.gridLayout_3.addWidget(self.bw_a_min, 5, 2, 1, 1)
		self.bw_mean_min = QtGui.QLineEdit(self.tab_2)
		self.bw_mean_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_mean_min.setObjectName(_fromUtf8("bw_mean_min"))
		self.gridLayout_3.addWidget(self.bw_mean_min, 3, 2, 1, 1)
		self.bw_a_max = QtGui.QLineEdit(self.tab_2)
		self.bw_a_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_a_max.setObjectName(_fromUtf8("bw_a_max"))
		self.gridLayout_3.addWidget(self.bw_a_max, 5, 3, 1, 1)
		self.label_22 = QtGui.QLabel(self.tab_2)
		self.label_22.setObjectName(_fromUtf8("label_22"))
		self.gridLayout_3.addWidget(self.label_22, 2, 1, 1, 1)
		self.label_23 = QtGui.QLabel(self.tab_2)
		self.label_23.setObjectName(_fromUtf8("label_23"))
		self.gridLayout_3.addWidget(self.label_23, 2, 2, 1, 1)
		self.bw_width_min = QtGui.QLineEdit(self.tab_2)
		self.bw_width_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_width_min.setObjectName(_fromUtf8("bw_width_min"))
		self.gridLayout_3.addWidget(self.bw_width_min, 4, 2, 1, 1)
		self.label_19 = QtGui.QLabel(self.tab_2)
		self.label_19.setObjectName(_fromUtf8("label_19"))
		self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
		self.label_16 = QtGui.QLabel(self.tab_2)
		self.label_16.setObjectName(_fromUtf8("label_16"))
		self.gridLayout_3.addWidget(self.label_16, 2, 3, 1, 1)
		self.bw_width_err = QtGui.QLabel(self.tab_2)
		self.bw_width_err.setText(_fromUtf8(""))
		self.bw_width_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_width_err.setObjectName(_fromUtf8("bw_width_err"))
		self.gridLayout_3.addWidget(self.bw_width_err, 4, 4, 1, 1)
		self.bw_width = QtGui.QLineEdit(self.tab_2)
		self.bw_width.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_width.setObjectName(_fromUtf8("bw_width"))
		self.gridLayout_3.addWidget(self.bw_width, 4, 1, 1, 1)
		self.label_21 = QtGui.QLabel(self.tab_2)
		self.label_21.setMinimumSize(QtCore.QSize(133, 0))
		self.label_21.setObjectName(_fromUtf8("label_21"))
		self.gridLayout_3.addWidget(self.label_21, 4, 0, 1, 1)
		self.bw_mean_err = QtGui.QLabel(self.tab_2)
		self.bw_mean_err.setText(_fromUtf8(""))
		self.bw_mean_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_mean_err.setObjectName(_fromUtf8("bw_mean_err"))
		self.gridLayout_3.addWidget(self.bw_mean_err, 3, 4, 1, 1)
		self.bw_mean_max = QtGui.QLineEdit(self.tab_2)
		self.bw_mean_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_mean_max.setObjectName(_fromUtf8("bw_mean_max"))
		self.gridLayout_3.addWidget(self.bw_mean_max, 3, 3, 1, 1)
		self.bw_b_max = QtGui.QLineEdit(self.tab_2)
		self.bw_b_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_b_max.setObjectName(_fromUtf8("bw_b_max"))
		self.gridLayout_3.addWidget(self.bw_b_max, 6, 3, 1, 1)
		self.bw_num_signal = QtGui.QLabel(self.tab_2)
		self.bw_num_signal.setText(_fromUtf8(""))
		self.bw_num_signal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_num_signal.setObjectName(_fromUtf8("bw_num_signal"))
		self.gridLayout_3.addWidget(self.bw_num_signal, 7, 3, 1, 1)
		self.bw_num_signal_err = QtGui.QLabel(self.tab_2)
		self.bw_num_signal_err.setText(_fromUtf8(""))
		self.bw_num_signal_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bw_num_signal_err.setObjectName(_fromUtf8("bw_num_signal_err"))
		self.gridLayout_3.addWidget(self.bw_num_signal_err, 7, 4, 1, 1)
		self.label_9 = QtGui.QLabel(self.tab_2)
		self.label_9.setObjectName(_fromUtf8("label_9"))
		self.gridLayout_3.addWidget(self.label_9, 7, 2, 1, 1)
		self.bw_del_fit = QtGui.QPushButton(self.tab_2)
		self.bw_del_fit.setObjectName(_fromUtf8("bw_del_fit"))
		self.gridLayout_3.addWidget(self.bw_del_fit, 8, 3, 1, 1)
		self.verticalLayout_3.addLayout(self.gridLayout_3)
		self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
		self.tab = QtGui.QWidget()
		self.tab.setObjectName(_fromUtf8("tab"))
		self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
		self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
		self.gridLayout_4 = QtGui.QGridLayout()
		self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
		self.label_27 = QtGui.QLabel(self.tab)
		self.label_27.setObjectName(_fromUtf8("label_27"))
		self.gridLayout_4.addWidget(self.label_27, 6, 0, 1, 1)
		self.voigt_width_max = QtGui.QLineEdit(self.tab)
		self.voigt_width_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_width_max.setObjectName(_fromUtf8("voigt_width_max"))
		self.gridLayout_4.addWidget(self.voigt_width_max, 4, 3, 1, 1)
		self.voigt_width_min = QtGui.QLineEdit(self.tab)
		self.voigt_width_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_width_min.setObjectName(_fromUtf8("voigt_width_min"))
		self.gridLayout_4.addWidget(self.voigt_width_min, 4, 2, 1, 1)
		self.label_30 = QtGui.QLabel(self.tab)
		self.label_30.setObjectName(_fromUtf8("label_30"))
		self.gridLayout_4.addWidget(self.label_30, 2, 2, 1, 1)
		self.voigt_a = QtGui.QLineEdit(self.tab)
		self.voigt_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_a.setObjectName(_fromUtf8("voigt_a"))
		self.gridLayout_4.addWidget(self.voigt_a, 6, 1, 1, 1)
		self.voigt_b = QtGui.QLineEdit(self.tab)
		self.voigt_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_b.setObjectName(_fromUtf8("voigt_b"))
		self.gridLayout_4.addWidget(self.voigt_b, 7, 1, 1, 1)
		self.label_31 = QtGui.QLabel(self.tab)
		self.label_31.setObjectName(_fromUtf8("label_31"))
		self.gridLayout_4.addWidget(self.label_31, 7, 0, 1, 1)
		self.voigt_a_max = QtGui.QLineEdit(self.tab)
		self.voigt_a_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_a_max.setObjectName(_fromUtf8("voigt_a_max"))
		self.gridLayout_4.addWidget(self.voigt_a_max, 6, 3, 1, 1)
		self.label_29 = QtGui.QLabel(self.tab)
		self.label_29.setObjectName(_fromUtf8("label_29"))
		self.gridLayout_4.addWidget(self.label_29, 2, 1, 1, 1)
		self.voigt_b_max = QtGui.QLineEdit(self.tab)
		self.voigt_b_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_b_max.setObjectName(_fromUtf8("voigt_b_max"))
		self.gridLayout_4.addWidget(self.voigt_b_max, 7, 3, 1, 1)
		self.voigt_b_min = QtGui.QLineEdit(self.tab)
		self.voigt_b_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_b_min.setObjectName(_fromUtf8("voigt_b_min"))
		self.gridLayout_4.addWidget(self.voigt_b_min, 7, 2, 1, 1)
		self.voigt_width_err = QtGui.QLabel(self.tab)
		self.voigt_width_err.setText(_fromUtf8(""))
		self.voigt_width_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_width_err.setObjectName(_fromUtf8("voigt_width_err"))
		self.gridLayout_4.addWidget(self.voigt_width_err, 4, 4, 1, 1)
		self.voigt_a_min = QtGui.QLineEdit(self.tab)
		self.voigt_a_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_a_min.setObjectName(_fromUtf8("voigt_a_min"))
		self.gridLayout_4.addWidget(self.voigt_a_min, 6, 2, 1, 1)
		self.do_voigtfit = QtGui.QPushButton(self.tab)
		self.do_voigtfit.setMinimumSize(QtCore.QSize(134, 0))
		self.do_voigtfit.setObjectName(_fromUtf8("do_voigtfit"))
		self.gridLayout_4.addWidget(self.do_voigtfit, 9, 4, 1, 1)
		self.label_26 = QtGui.QLabel(self.tab)
		self.label_26.setObjectName(_fromUtf8("label_26"))
		self.gridLayout_4.addWidget(self.label_26, 0, 1, 1, 1)
		self.label_28 = QtGui.QLabel(self.tab)
		self.label_28.setObjectName(_fromUtf8("label_28"))
		self.gridLayout_4.addWidget(self.label_28, 0, 4, 1, 1)
		self.voigt_b_err = QtGui.QLabel(self.tab)
		self.voigt_b_err.setText(_fromUtf8(""))
		self.voigt_b_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_b_err.setObjectName(_fromUtf8("voigt_b_err"))
		self.gridLayout_4.addWidget(self.voigt_b_err, 7, 4, 1, 1)
		self.voigt_mean = QtGui.QLineEdit(self.tab)
		self.voigt_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_mean.setObjectName(_fromUtf8("voigt_mean"))
		self.gridLayout_4.addWidget(self.voigt_mean, 3, 1, 1, 1)
		self.label_25 = QtGui.QLabel(self.tab)
		self.label_25.setObjectName(_fromUtf8("label_25"))
		self.gridLayout_4.addWidget(self.label_25, 3, 0, 1, 1)
		self.voigt_a_err = QtGui.QLabel(self.tab)
		self.voigt_a_err.setText(_fromUtf8(""))
		self.voigt_a_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_a_err.setObjectName(_fromUtf8("voigt_a_err"))
		self.gridLayout_4.addWidget(self.voigt_a_err, 6, 4, 1, 1)
		self.voigt_mean_min = QtGui.QLineEdit(self.tab)
		self.voigt_mean_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_mean_min.setObjectName(_fromUtf8("voigt_mean_min"))
		self.gridLayout_4.addWidget(self.voigt_mean_min, 3, 2, 1, 1)
		self.voigt_mean_err = QtGui.QLabel(self.tab)
		self.voigt_mean_err.setText(_fromUtf8(""))
		self.voigt_mean_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_mean_err.setObjectName(_fromUtf8("voigt_mean_err"))
		self.gridLayout_4.addWidget(self.voigt_mean_err, 3, 4, 1, 1)
		self.label_32 = QtGui.QLabel(self.tab)
		self.label_32.setObjectName(_fromUtf8("label_32"))
		self.gridLayout_4.addWidget(self.label_32, 2, 3, 1, 1)
		self.voigt_width = QtGui.QLineEdit(self.tab)
		self.voigt_width.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_width.setObjectName(_fromUtf8("voigt_width"))
		self.gridLayout_4.addWidget(self.voigt_width, 4, 1, 1, 1)
		self.voigt_mean_max = QtGui.QLineEdit(self.tab)
		self.voigt_mean_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_mean_max.setObjectName(_fromUtf8("voigt_mean_max"))
		self.gridLayout_4.addWidget(self.voigt_mean_max, 3, 3, 1, 1)
		self.label_33 = QtGui.QLabel(self.tab)
		self.label_33.setObjectName(_fromUtf8("label_33"))
		self.gridLayout_4.addWidget(self.label_33, 4, 0, 1, 1)
		self.label_7 = QtGui.QLabel(self.tab)
		self.label_7.setMinimumSize(QtCore.QSize(133, 0))
		self.label_7.setObjectName(_fromUtf8("label_7"))
		self.gridLayout_4.addWidget(self.label_7, 5, 0, 1, 1)
		self.voigt_sigma = QtGui.QLineEdit(self.tab)
		self.voigt_sigma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_sigma.setObjectName(_fromUtf8("voigt_sigma"))
		self.gridLayout_4.addWidget(self.voigt_sigma, 5, 1, 1, 1)
		self.voigt_sigma_min = QtGui.QLineEdit(self.tab)
		self.voigt_sigma_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_sigma_min.setObjectName(_fromUtf8("voigt_sigma_min"))
		self.gridLayout_4.addWidget(self.voigt_sigma_min, 5, 2, 1, 1)
		self.voigt_sigma_max = QtGui.QLineEdit(self.tab)
		self.voigt_sigma_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_sigma_max.setObjectName(_fromUtf8("voigt_sigma_max"))
		self.gridLayout_4.addWidget(self.voigt_sigma_max, 5, 3, 1, 1)
		self.voigt_sigma_err = QtGui.QLabel(self.tab)
		self.voigt_sigma_err.setText(_fromUtf8(""))
		self.voigt_sigma_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_sigma_err.setObjectName(_fromUtf8("voigt_sigma_err"))
		self.gridLayout_4.addWidget(self.voigt_sigma_err, 5, 4, 1, 1)
		self.voigt_num_signal = QtGui.QLabel(self.tab)
		self.voigt_num_signal.setText(_fromUtf8(""))
		self.voigt_num_signal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_num_signal.setObjectName(_fromUtf8("voigt_num_signal"))
		self.gridLayout_4.addWidget(self.voigt_num_signal, 8, 3, 1, 1)
		self.voigt_num_signal_err = QtGui.QLabel(self.tab)
		self.voigt_num_signal_err.setText(_fromUtf8(""))
		self.voigt_num_signal_err.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.voigt_num_signal_err.setObjectName(_fromUtf8("voigt_num_signal_err"))
		self.gridLayout_4.addWidget(self.voigt_num_signal_err, 8, 4, 1, 1)
		self.label_11 = QtGui.QLabel(self.tab)
		self.label_11.setObjectName(_fromUtf8("label_11"))
		self.gridLayout_4.addWidget(self.label_11, 8, 2, 1, 1)
		self.voigt_del_fit = QtGui.QPushButton(self.tab)
		self.voigt_del_fit.setObjectName(_fromUtf8("voigt_del_fit"))
		self.gridLayout_4.addWidget(self.voigt_del_fit, 9, 3, 1, 1)
		self.verticalLayout_4.addLayout(self.gridLayout_4)
		self.tabWidget.addTab(self.tab, _fromUtf8(""))
		self.verticalLayout.addWidget(self.tabWidget)
		fitpannel.setCentralWidget(self.centralwidget)

		self.retranslateUi(fitpannel)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(fitpannel)
		fitpannel.setTabOrder(self.tabWidget, self.gauss_mean)
		fitpannel.setTabOrder(self.gauss_mean, self.gauss_mean_min)
		fitpannel.setTabOrder(self.gauss_mean_min, self.gauss_mean_max)
		fitpannel.setTabOrder(self.gauss_mean_max, self.gauss_sigma)
		fitpannel.setTabOrder(self.gauss_sigma, self.gauss_sigma_min)
		fitpannel.setTabOrder(self.gauss_sigma_min, self.gauss_sigma_max)
		fitpannel.setTabOrder(self.gauss_sigma_max, self.gauss_a)
		fitpannel.setTabOrder(self.gauss_a, self.gauss_a_min)
		fitpannel.setTabOrder(self.gauss_a_min, self.gauss_a_max)
		fitpannel.setTabOrder(self.gauss_a_max, self.gauss_b)
		fitpannel.setTabOrder(self.gauss_b, self.gauss_b_min)
		fitpannel.setTabOrder(self.gauss_b_min, self.gauss_b_max)
		fitpannel.setTabOrder(self.gauss_b_max, self.do_gaussfit)
		fitpannel.setTabOrder(self.do_gaussfit, self.bw_mean)
		fitpannel.setTabOrder(self.bw_mean, self.bw_mean_min)
		fitpannel.setTabOrder(self.bw_mean_min, self.bw_mean_max)
		fitpannel.setTabOrder(self.bw_mean_max, self.bw_width)
		fitpannel.setTabOrder(self.bw_width, self.bw_width_min)
		fitpannel.setTabOrder(self.bw_width_min, self.bw_width_max)
		fitpannel.setTabOrder(self.bw_width_max, self.bw_a)
		fitpannel.setTabOrder(self.bw_a, self.bw_a_min)
		fitpannel.setTabOrder(self.bw_a_min, self.bw_a_max)
		fitpannel.setTabOrder(self.bw_a_max, self.bw_b)
		fitpannel.setTabOrder(self.bw_b, self.bw_b_min)
		fitpannel.setTabOrder(self.bw_b_min, self.bw_b_max)
		fitpannel.setTabOrder(self.bw_b_max, self.do_bwfit)
		fitpannel.setTabOrder(self.do_bwfit, self.voigt_mean)
		fitpannel.setTabOrder(self.voigt_mean, self.voigt_mean_min)
		fitpannel.setTabOrder(self.voigt_mean_min, self.voigt_mean_max)
		fitpannel.setTabOrder(self.voigt_mean_max, self.voigt_width)
		fitpannel.setTabOrder(self.voigt_width, self.voigt_width_min)
		fitpannel.setTabOrder(self.voigt_width_min, self.voigt_width_max)
		fitpannel.setTabOrder(self.voigt_width_max, self.voigt_sigma)
		fitpannel.setTabOrder(self.voigt_sigma, self.voigt_sigma_min)
		fitpannel.setTabOrder(self.voigt_sigma_min, self.voigt_sigma_max)
		fitpannel.setTabOrder(self.voigt_sigma_max, self.voigt_a)
		fitpannel.setTabOrder(self.voigt_a, self.voigt_a_min)
		fitpannel.setTabOrder(self.voigt_a_min, self.voigt_a_max)
		fitpannel.setTabOrder(self.voigt_a_max, self.voigt_b)
		fitpannel.setTabOrder(self.voigt_b, self.voigt_b_min)
		fitpannel.setTabOrder(self.voigt_b_min, self.voigt_b_max)
		fitpannel.setTabOrder(self.voigt_b_max, self.do_voigtfit)

	def retranslateUi(self, fitpannel):
		fitpannel.setWindowTitle(QtGui.QApplication.translate("fitpannel", "Fit Bedienoberfläche", None, QtGui.QApplication.UnicodeUTF8))
		self.label_15.setText(QtGui.QApplication.translate("fitpannel", "Derzeit", None, QtGui.QApplication.UnicodeUTF8))
		self.do_gaussfit.setText(QtGui.QApplication.translate("fitpannel", "Fitte Gauß", None, QtGui.QApplication.UnicodeUTF8))
		self.label_5.setText(QtGui.QApplication.translate("fitpannel", "a", None, QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("fitpannel", "Standardabweichung", None, QtGui.QApplication.UnicodeUTF8))
		self.label_14.setText(QtGui.QApplication.translate("fitpannel", "Max", None, QtGui.QApplication.UnicodeUTF8))
		self.label_13.setText(QtGui.QApplication.translate("fitpannel", "Min", None, QtGui.QApplication.UnicodeUTF8))
		self.label_4.setText(QtGui.QApplication.translate("fitpannel", "Fehler", None, QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("fitpannel", "Mittelwert", None, QtGui.QApplication.UnicodeUTF8))
		self.label_6.setText(QtGui.QApplication.translate("fitpannel", "b", None, QtGui.QApplication.UnicodeUTF8))
		self.label_3.setText(QtGui.QApplication.translate("fitpannel", "Werte", None, QtGui.QApplication.UnicodeUTF8))
		self.label_8.setText(QtGui.QApplication.translate("fitpannel", "Anz. Signalevents", None, QtGui.QApplication.UnicodeUTF8))
		self.gauss_del_fit.setText(QtGui.QApplication.translate("fitpannel", "Lösche Fit", None, QtGui.QApplication.UnicodeUTF8))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.gauss), QtGui.QApplication.translate("fitpannel", "Gauß", None, QtGui.QApplication.UnicodeUTF8))
		self.label_18.setText(QtGui.QApplication.translate("fitpannel", "Mittelwert", None, QtGui.QApplication.UnicodeUTF8))
		self.label_20.setText(QtGui.QApplication.translate("fitpannel", "Werte", None, QtGui.QApplication.UnicodeUTF8))
		self.label_17.setText(QtGui.QApplication.translate("fitpannel", "a", None, QtGui.QApplication.UnicodeUTF8))
		self.do_bwfit.setText(QtGui.QApplication.translate("fitpannel", "Fitte Breit-Wigner", None, QtGui.QApplication.UnicodeUTF8))
		self.label_24.setText(QtGui.QApplication.translate("fitpannel", "Fehler", None, QtGui.QApplication.UnicodeUTF8))
		self.label_22.setText(QtGui.QApplication.translate("fitpannel", "Derzeit", None, QtGui.QApplication.UnicodeUTF8))
		self.label_23.setText(QtGui.QApplication.translate("fitpannel", "Min", None, QtGui.QApplication.UnicodeUTF8))
		self.label_19.setText(QtGui.QApplication.translate("fitpannel", "b", None, QtGui.QApplication.UnicodeUTF8))
		self.label_16.setText(QtGui.QApplication.translate("fitpannel", "Max", None, QtGui.QApplication.UnicodeUTF8))
		self.label_21.setText(QtGui.QApplication.translate("fitpannel", "Breite", None, QtGui.QApplication.UnicodeUTF8))
		self.label_9.setText(QtGui.QApplication.translate("fitpannel", "Anz. Signalevents", None, QtGui.QApplication.UnicodeUTF8))
		self.bw_del_fit.setText(QtGui.QApplication.translate("fitpannel", "Lösche Fit", None, QtGui.QApplication.UnicodeUTF8))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("fitpannel", "Breit-Wigner", None, QtGui.QApplication.UnicodeUTF8))
		self.label_27.setText(QtGui.QApplication.translate("fitpannel", "a", None, QtGui.QApplication.UnicodeUTF8))
		self.label_30.setText(QtGui.QApplication.translate("fitpannel", "Min", None, QtGui.QApplication.UnicodeUTF8))
		self.label_31.setText(QtGui.QApplication.translate("fitpannel", "b", None, QtGui.QApplication.UnicodeUTF8))
		self.label_29.setText(QtGui.QApplication.translate("fitpannel", "Derzeit", None, QtGui.QApplication.UnicodeUTF8))
		self.do_voigtfit.setText(QtGui.QApplication.translate("fitpannel", "Fitte Voigt", None, QtGui.QApplication.UnicodeUTF8))
		self.label_26.setText(QtGui.QApplication.translate("fitpannel", "Werte", None, QtGui.QApplication.UnicodeUTF8))
		self.label_28.setText(QtGui.QApplication.translate("fitpannel", "Fehler", None, QtGui.QApplication.UnicodeUTF8))
		self.label_25.setText(QtGui.QApplication.translate("fitpannel", "Mittelwert", None, QtGui.QApplication.UnicodeUTF8))
		self.label_32.setText(QtGui.QApplication.translate("fitpannel", "Max", None, QtGui.QApplication.UnicodeUTF8))
		self.label_33.setText(QtGui.QApplication.translate("fitpannel", "Breite (Breit-Wigner)", None, QtGui.QApplication.UnicodeUTF8))
		self.label_7.setText(QtGui.QApplication.translate("fitpannel", "Sigma (Gauss)", None, QtGui.QApplication.UnicodeUTF8))
		self.label_11.setText(QtGui.QApplication.translate("fitpannel", "Anz. Signalevents", None, QtGui.QApplication.UnicodeUTF8))
		self.voigt_del_fit.setText(QtGui.QApplication.translate("fitpannel", "Lösche Fit", None, QtGui.QApplication.UnicodeUTF8))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("fitpannel", "Voigt", None, QtGui.QApplication.UnicodeUTF8))

